const strings = {
  'en-US': {
    'app.http.404': 'Page Not Found',
    'app.http.404.redirect': 'Perhaps you were looking for {url}',
    'app.title': 'Prephouse',
    'actionbar.dropdown.item.darkMode': 'Dark Mode',
    'about.title': 'About',
    'about.team': 'Our team',
    'compare.title': 'Compare',
    'dashboard.title': 'My Progress',
    'general.action.website': 'Website',
    'general.action.linkedin': 'LinkedIn',
    'general.action.github': 'GitHub',
    'general.field.requiredField': 'Required field',
    'practice.step.selectSettings': 'Select your settings',
    'practice.step.readInstructions': 'Review instructions',
    'practice.step.practice': 'Practice!',
    'practice.title': 'Practice',
    'practice.title.expanded': 'Practice Ground',
    'practice.upload': 'Upload an existing mock interview or presentation',
    'practice.upload.dragDropClick':
      'Drag and drop a video or audio file here, or click here to select a file',
    'practice.upload.dropImage': 'Drop a video or audio file file here',
    'practice.upload.mime.error': 'We cannot accept this file',
    'practice.upload.mime.warning': '...',
    'tips.title': 'Tips',
    'tips.title.expanded': 'Tips for success',
    'user.sign-in.action': 'Sign in',
    'user.registration.action': 'Create new account',
    'user.registration.title': 'Create your personalized account',
    'user.registration.email': 'Email Address',
    'user.registration.firstName': 'First Name',
    'user.registration.lastName': 'Last Name',
    'user.registration.password': 'Password',
    'user.registration.passwordConfirmation': 'Password Confirmation',
    'user.registration.age.minimum': 'You must be at least 16 years old to create an account',
    'user.registration.email.error': 'Invalid email address',
    'user.registration.password.error': 'Password must contain {passwordErrorMsg}',
    'user.registration.password.requirement': 'Password must contain',
    'user.registration.password.match': 'Passwords do not match',
    'user.registration.password.length': 'At least 8 characters',
    'user.registration.password.oneNumber': 'At least 1 number',
    'user.registration.password.oneUpper': 'At least 1 uppercase letter',
    'user.registration.password.strength.0': 'Extremely Weak',
    'user.registration.password.strength.1': 'Very Weak',
    'user.registration.password.strength.2': 'Weak',
    'user.registration.password.strength.3': 'Adequate',
    'user.registration.password.strength.4': 'Strong',
    'user.registration.password.strength.aria': 'password strength meter',
    'user.registration.clear': 'Clear fields',
    'user.registration.register': 'Create account',
  },
};

export default strings;
